version: '3.8'

services:
  # Servicio de la aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conradmed_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - conradmed_network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: conradmed_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - conradmed_network
    depends_on:
      - app

  # Servicio de MySQL
  db:
    image: mysql:8.0
    container_name: conradmed_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: conradmed
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: conradmed
      MYSQL_PASSWORD: conradmed123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - conradmed_network

  # Servicio de phpMyAdmin (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: conradmed_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - conradmed_network
    depends_on:
      - db

volumes:
  dbdata:
    driver: local

networks:
  conradmed_network:
    driver: bridge 